### ISSUE TITLE
initialize.py: error: unrecognized arguments: -server XXX.XXX.X.XXX:10009, after updating to v1.9.0

### ISSUE THREAD

**Issue by alex-btc** [cryptosharks131/lndg#396]
After updating the docker version to lndg v1.9.0, I cannot start it anymore.

When running `docker-compose up` it crashes with the following message:

`initialize.py: error: unrecognized arguments: -server XXX.XXX.X.XXX:10009`

This did not occour in the previous message.

My `docker-compose.yaml` file is as follows:

```
services:
  lndg:
    build: .
    volumes:
      - /home/XXXXX/.lnd:/root/.lnd:ro
      - /home/XXXXX/lndg/data:/lndg/data:rw
    command:
      - sh
      - -c
      - python initialize.py -net 'mainnet' -server 'XXX.XXX.X.XXX:10009' -d && supervisord && python manage.py runserver 0:8000
    ports:
      - 8889:8000
```
