### ISSUE TITLE
Unsupported config option for services: 'lndg'

### ISSUE THREAD

**Issue by benthecarman** [cryptosharks131/lndg#67]
I am trying to install using docker compose

I am currently getting this error
```bash
$ docker-compose up -d
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'lndg'
```

docker file:

```
services:
  lndg:
    build: .
    volumes:
      - /home/ben/.lnd:/root/.lnd:ro
      - /home/ben/projects/lndg/data:/lndg/data:rw
    command:
      - sh
      - -c
      - python initialize.py -net 'mainnet' -server '127.0.0.1:10009' -d && supervisord && python manage.py runserver 0.0.0.0:8889
    network_mode: "host"
```

docker versions:
```
$ docker-compose --version
docker-compose version 1.25.0, build unknown
$ docker --version
Docker version 20.10.16, build aa7e414
```

**Comment by cryptosharks131** [comment]
Can you change line 5 of the docker-compose by removing the `:rw` and see if that resolves the issue?

`- /home/ben/projects/lndg/data:/lndg/data`

**Comment by benthecarman** [comment]
> Can you change line 5 of the docker-compose by removing the `:rw` and see if that resolves the issue?
> 
> `- /home/ben/projects/lndg/data:/lndg/data`

Did not fix, same issue

**Comment by cryptosharks131** [comment]
Interesting, can you try another docker-compose.yaml that uses `ports` instead of the `network_mode` option?
```
services:
  lndg:
    build: .
    volumes:
      - /home/ben/.lnd:/root/.lnd:ro
      - /home/ben/projects/lndg/data:/lndg/data
    command:
      - sh
      - -c
      - python initialize.py -net 'mainnet' -server 'localhost:10009' -d && supervisord && python manage.py runserver 0.0.0.0:8000
    ports:
      - 8889:8000
 ```

**Comment by benthecarman** [comment]
> Interesting, can you try another docker-compose.yaml that uses ports instead of the network_mode option?

same issue again :/

**Comment by cryptosharks131** [comment]
Very strange, maybe try recreating the file, just in case a strange character jumped in there. These files can be very picky and I have seen that cause an issue as well.

If that doesn't help, other thoughts would be, maybe you could try it without the services.
```
lndg:
  build: .
  volumes:
    - /home/ben/.lnd:/root/.lnd:ro
    - /home/ben/projects/lndg/data:/lndg/data
  command:
    - sh
    - -c
    - python initialize.py -net 'mainnet' -server 'localhost:10009' -d && supervisord && python manage.py runserver 0.0.0.0:8000
  ports:
    - 8889:8000
```
